### PR TITLE
First try at a README.md

### PR DESCRIPTION
**Pull request by alecrem**

### CODE REVIEW

**Comment by alecrem** [comment]
@adetokunbo feel free to commit over this or just tell me what you would like to change

**Comment by adetokunbo** [comment]
Thanks! This is great start to the README.md.
I can't see anything wrong with the information in it so far, so lets submit this and keep tweaking it.

**Review by adetokunbo — APPROVED** [review]
Looks good, thank you!

**Comment by alecrem** [comment]
I did "merge and rebase" and it shows as a bare commit on master... Sorry. Should I have "created a merge commit"?

**Pull request merged**
